### ISSUE TITLE
loading属于按钮样式不

### ISSUE THREAD

**Issue by xuexb** [rain-team/ui-button#1]
RT, look [demo](http://github.xuexb.com/demo/btn/ui.html)

**Comment by nimojs** [comment]
我们目前的业务场景考虑在按钮内部里面加 img

**Comment by xuexb** [comment]
@nimojs 哦，我只是想使用一个合理的`dom`结构，然后只操作`className`来展示不同的`UI`，比如大小，禁用，加载中，颜色等，跟你的思路一致，啦啦啦～

**Comment by nimojs** [comment]
我是基于 https://github.com/aliceui/button 修改的


[规范和最佳实践](http://aliceui.org/docs/rule.html) 这个很好，你可以看看。


```
class="ui-btn disabled"
// 可改为
class="ui-btn ui-btn-disabled"
```
以前踩过这个坑，没有按照这个规范和最佳实践导致样式冲突，很麻烦。

**Comment by xuexb** [comment]
@nimojs 恩，那是以前设计的想法，现在我也是`标识-模块名-*`来定，标识分全局，工具，ui，页面 等，3q
